### ISSUE TITLE
FYI - Broken on Catalina...

### ISSUE THREAD

**Issue by XReyRobert** [hhas/Swift-AppleScriptObjC#1]

**Comment by hhas** [comment]
Apple renamed iTunes.app to Music.app in macOS 10.15, therefore there are two changes required:

1. Replace “iTunes” with “Music”.

2. Replace Apple management with people who know how to build robust, secure, competent platforms that serve their users’ needs, not their bean counters’.

HTH.

**Comment by hhas** [comment]
That’s not a dig at you, reporter, BTW. I genuinely appreciate the input, but it’s clear Apple don’t give a flying f*ck about breaking this stuff, so I just can’t be any longer. Not my product; not my battle. Sorry.
